# Module 2: NumPy Comprehensive Test - SOLUTIONS

This test covers all topics from Module 2 (NumPy). Complete each exercise in the provided code cells.

**Topics Covered:**
- Array Fundamentals (creation, dtypes, shape)
- Indexing and Slicing (basic, fancy, boolean)
- Array Operations (arithmetic, ufuncs, aggregations)
- Broadcasting and Vectorization
- Linear Algebra and Random Numbers

**Instructions:**
1. Run the setup cell below first
2. Read each question carefully
3. Write your solution in the provided code cell
4. Test your solution by running the cell

In [ ]:
# Setup - Run this cell first!
import numpy as np
print(f"NumPy version: {np.__version__}")
print("Setup complete!")

---
## Section 1: Array Fundamentals
---

### Question 1: Array Creation

Create the following arrays:
1. A 1D array named `arr1` containing the integers 1 through 10 (inclusive)
2. A 2D array named `arr2` with shape (3, 4) filled with zeros
3. A 1D array named `arr3` with 5 evenly spaced values between 0 and 1 (inclusive)

Print each array and its shape.

In [ ]:
# Solution

# 1. 1D array with integers 1-10
arr1 = np.arange(1, 11)
print("arr1:", arr1)
print("Shape:", arr1.shape)
print()

# 2. 2D array of zeros with shape (3, 4)
arr2 = np.zeros((3, 4))
print("arr2:")
print(arr2)
print("Shape:", arr2.shape)
print()

# 3. 5 evenly spaced values between 0 and 1
arr3 = np.linspace(0, 1, 5)
print("arr3:", arr3)
print("Shape:", arr3.shape)

### Question 2: Data Types

1. Create an array `int_arr` containing [1, 2, 3, 4, 5] with dtype `int32`
2. Create an array `float_arr` by converting `int_arr` to `float64`
3. Create a boolean array `bool_arr` from the list [True, False, True, True, False]

Print each array along with its dtype.

In [ ]:
# Solution

# 1. Create int32 array
int_arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)
print("int_arr:", int_arr)
print("dtype:", int_arr.dtype)
print()

# 2. Convert to float64
float_arr = int_arr.astype(np.float64)
print("float_arr:", float_arr)
print("dtype:", float_arr.dtype)
print()

# 3. Boolean array
bool_arr = np.array([True, False, True, True, False])
print("bool_arr:", bool_arr)
print("dtype:", bool_arr.dtype)

### Question 3: Reshaping Arrays

1. Create an array with values 1 through 24
2. Reshape it to a 3D array with shape (2, 3, 4)
3. Flatten the 3D array back to 1D using two different methods

Print the original array, reshaped array, and both flattened versions with their shapes.

In [ ]:
# Solution

# 1. Create array 1-24
original = np.arange(1, 25)
print("Original array:", original)
print("Shape:", original.shape)
print()

# 2. Reshape to 3D (2, 3, 4)
reshaped = original.reshape(2, 3, 4)
print("Reshaped (2, 3, 4):")
print(reshaped)
print("Shape:", reshaped.shape)
print()

# 3. Flatten using two methods
# Method 1: .flatten() - returns a copy
flat1 = reshaped.flatten()
print("Flattened (using .flatten()):", flat1)
print("Shape:", flat1.shape)
print()

# Method 2: .ravel() - returns a view when possible
flat2 = reshaped.ravel()
print("Flattened (using .ravel()):", flat2)
print("Shape:", flat2.shape)

---
## Section 2: Indexing and Slicing
---

### Question 4: Basic Indexing and Slicing

Given the array below:
```python
matrix = np.arange(1, 26).reshape(5, 5)
```

Extract:
1. The element at row 2, column 3 (0-indexed)
2. The entire third row
3. The entire second column
4. A 2x2 subarray from the bottom-right corner

In [ ]:
# Solution
matrix = np.arange(1, 26).reshape(5, 5)
print("Original matrix:")
print(matrix)
print()

# 1. Element at row 2, column 3
element = matrix[2, 3]
print("1. Element at [2, 3]:", element)
print()

# 2. Entire third row (index 2)
third_row = matrix[2, :]
print("2. Third row:", third_row)
print()

# 3. Entire second column (index 1)
second_col = matrix[:, 1]
print("3. Second column:", second_col)
print()

# 4. 2x2 subarray from bottom-right corner
bottom_right = matrix[-2:, -2:]
print("4. Bottom-right 2x2:")
print(bottom_right)

### Question 5: Fancy Indexing

Using the same matrix from Question 4:
1. Select rows 0, 2, and 4 simultaneously
2. Select the elements at positions (0,0), (1,2), (3,4) in a single operation
3. Reorder the columns to be [4, 2, 0, 3, 1] (reverse every other column)

In [ ]:
# Solution
matrix = np.arange(1, 26).reshape(5, 5)
print("Original matrix:")
print(matrix)
print()

# 1. Select rows 0, 2, and 4
selected_rows = matrix[[0, 2, 4], :]
print("1. Rows 0, 2, and 4:")
print(selected_rows)
print()

# 2. Select elements at (0,0), (1,2), (3,4)
elements = matrix[[0, 1, 3], [0, 2, 4]]
print("2. Elements at (0,0), (1,2), (3,4):", elements)
print()

# 3. Reorder columns to [4, 2, 0, 3, 1]
reordered = matrix[:, [4, 2, 0, 3, 1]]
print("3. Reordered columns [4, 2, 0, 3, 1]:")
print(reordered)

### Question 6: Boolean Indexing

Given the array:
```python
data = np.array([12, 5, 18, 3, 21, 8, 15, 2, 19, 7])
```

1. Select all elements greater than 10
2. Select all elements that are even
3. Select all elements that are both greater than 5 AND less than 15
4. Replace all elements less than 10 with 0 (create a copy first)

In [ ]:
# Solution
data = np.array([12, 5, 18, 3, 21, 8, 15, 2, 19, 7])
print("Original data:", data)
print()

# 1. Elements greater than 10
greater_than_10 = data[data > 10]
print("1. Elements > 10:", greater_than_10)
print()

# 2. Even elements
even_elements = data[data % 2 == 0]
print("2. Even elements:", even_elements)
print()

# 3. Elements > 5 AND < 15
between_5_15 = data[(data > 5) & (data < 15)]
print("3. Elements > 5 and < 15:", between_5_15)
print()

# 4. Replace elements < 10 with 0 (using a copy)
data_copy = data.copy()
data_copy[data_copy < 10] = 0
print("4. After replacing < 10 with 0:", data_copy)
print("   Original unchanged:", data)

---
## Section 3: Array Operations
---

### Question 7: Arithmetic Operations and Universal Functions

Given:
```python
a = np.array([1, 4, 9, 16, 25])
b = np.array([1, 2, 3, 4, 5])
```

Calculate and print:
1. Element-wise addition of `a` and `b`
2. Element-wise division of `a` by `b`
3. Square root of each element in `a`
4. `b` raised to the power of 2
5. Natural logarithm of `a`

In [ ]:
# Solution
a = np.array([1, 4, 9, 16, 25])
b = np.array([1, 2, 3, 4, 5])
print("a:", a)
print("b:", b)
print()

# 1. Element-wise addition
addition = a + b
print("1. a + b =", addition)

# 2. Element-wise division
division = a / b
print("2. a / b =", division)

# 3. Square root of a
sqrt_a = np.sqrt(a)
print("3. sqrt(a) =", sqrt_a)

# 4. b squared
b_squared = b ** 2  # or np.power(b, 2)
print("4. b^2 =", b_squared)

# 5. Natural logarithm of a
log_a = np.log(a)
print("5. ln(a) =", log_a)

### Question 8: Aggregation Functions

Given the matrix:
```python
scores = np.array([[85, 90, 78],
                   [92, 88, 95],
                   [76, 82, 89],
                   [88, 91, 84]])
```
Where rows are students and columns are subjects (Math, Science, English).

Calculate:
1. The overall mean score
2. The mean score for each student (across subjects)
3. The mean score for each subject (across students)
4. The highest score in each subject
5. The standard deviation of all scores

In [ ]:
# Solution
scores = np.array([[85, 90, 78],
                   [92, 88, 95],
                   [76, 82, 89],
                   [88, 91, 84]])
print("Scores matrix:")
print(scores)
print("Subjects: Math, Science, English")
print()

# 1. Overall mean
overall_mean = np.mean(scores)
print(f"1. Overall mean: {overall_mean:.2f}")

# 2. Mean for each student (axis=1, across columns)
student_means = np.mean(scores, axis=1)
print(f"2. Mean per student: {student_means}")

# 3. Mean for each subject (axis=0, across rows)
subject_means = np.mean(scores, axis=0)
print(f"3. Mean per subject [Math, Science, English]: {subject_means}")

# 4. Highest score in each subject
max_per_subject = np.max(scores, axis=0)
print(f"4. Highest per subject: {max_per_subject}")

# 5. Standard deviation of all scores
std_all = np.std(scores)
print(f"5. Standard deviation: {std_all:.2f}")

---
## Section 4: Broadcasting and Vectorization
---

### Question 9: Broadcasting

1. Create a 4x4 matrix of ones
2. Create a 1D array [1, 2, 3, 4]
3. Use broadcasting to:
   - Multiply each row of the matrix by the 1D array
   - Add the 1D array as a column vector to each column of the matrix

Print intermediate results to show how broadcasting works.

In [ ]:
# Solution

# 1. Create 4x4 matrix of ones
matrix = np.ones((4, 4))
print("1. Matrix of ones (4x4):")
print(matrix)
print()

# 2. Create 1D array
arr = np.array([1, 2, 3, 4])
print("2. 1D array:", arr)
print("   Shape:", arr.shape)
print()

# 3a. Multiply each row by the 1D array
# Broadcasting: (4, 4) * (4,) -> (4, 4) * (1, 4) -> (4, 4)
row_multiply = matrix * arr
print("3a. Each row multiplied by [1, 2, 3, 4]:")
print(row_multiply)
print()

# 3b. Add 1D array as column vector to each column
# Need to reshape arr to (4, 1) for column broadcasting
col_vector = arr.reshape(4, 1)  # or arr[:, np.newaxis]
print("Column vector shape:", col_vector.shape)
col_add = matrix + col_vector
print("3b. Each column + [1, 2, 3, 4] (as column):")
print(col_add)

### Question 10: Vectorization Challenge

The following code uses Python loops to normalize each row of a matrix to have mean 0 and standard deviation 1:

```python
data = np.random.randn(100, 5)
normalized = np.zeros_like(data)
for i in range(data.shape[0]):
    row = data[i]
    mean = np.mean(row)
    std = np.std(row)
    normalized[i] = (row - mean) / std
```

Rewrite this using vectorized NumPy operations (no Python loops). Verify your result matches the loop version.

In [ ]:
# Solution
np.random.seed(42)  # For reproducibility
data = np.random.randn(100, 5)

# Loop version (for comparison)
normalized_loop = np.zeros_like(data)
for i in range(data.shape[0]):
    row = data[i]
    mean = np.mean(row)
    std = np.std(row)
    normalized_loop[i] = (row - mean) / std

# Vectorized version
# Calculate mean and std for each row (axis=1)
# keepdims=True maintains shape for broadcasting
row_means = np.mean(data, axis=1, keepdims=True)
row_stds = np.std(data, axis=1, keepdims=True)
normalized_vectorized = (data - row_means) / row_stds

# Verify results match
print("Results match:", np.allclose(normalized_loop, normalized_vectorized))
print()
print("First 3 rows of vectorized result:")
print(normalized_vectorized[:3])
print()
print("Verification - Row means (should be ~0):")
print(np.mean(normalized_vectorized, axis=1)[:5])
print()
print("Verification - Row stds (should be ~1):")
print(np.std(normalized_vectorized, axis=1)[:5])

---
## Section 5: Linear Algebra and Random Numbers
---

### Question 11: Matrix Operations

Given:
```python
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
```

Calculate:
1. Matrix multiplication of A and B (using @ operator or np.dot)
2. The transpose of A
3. The determinant of A
4. The inverse of A
5. Verify that A @ A_inverse equals the identity matrix

In [ ]:
# Solution
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("A:")
print(A)
print("\nB:")
print(B)
print()

# 1. Matrix multiplication
AB = A @ B  # or np.dot(A, B)
print("1. A @ B =")
print(AB)
print()

# 2. Transpose of A
A_T = A.T  # or np.transpose(A)
print("2. Transpose of A:")
print(A_T)
print()

# 3. Determinant of A
det_A = np.linalg.det(A)
print(f"3. Determinant of A: {det_A:.2f}")
print()

# 4. Inverse of A
A_inv = np.linalg.inv(A)
print("4. Inverse of A:")
print(A_inv)
print()

# 5. Verify A @ A_inv = Identity
identity_check = A @ A_inv
print("5. A @ A_inverse (should be identity):")
print(identity_check)
print("\nIs close to identity:", np.allclose(identity_check, np.eye(2)))

### Question 12: Solving Linear Systems

Solve the following system of linear equations using NumPy:

```
2x + 3y - z = 1
4x + y + 2z = 2  
3x + 2y + 3z = 3
```

Express this in matrix form (Ax = b) and solve for x, y, z. Verify your solution by computing A @ x.

In [ ]:
# Solution

# Express as Ax = b
# Coefficient matrix A
A = np.array([[2, 3, -1],
              [4, 1, 2],
              [3, 2, 3]])

# Constants vector b
b = np.array([1, 2, 3])

print("Coefficient matrix A:")
print(A)
print("\nConstants vector b:", b)
print()

# Solve the system
solution = np.linalg.solve(A, b)
x, y, z = solution

print(f"Solution:")
print(f"x = {x:.6f}")
print(f"y = {y:.6f}")
print(f"z = {z:.6f}")
print()

# Verify: A @ solution should equal b
verification = A @ solution
print("Verification (A @ x):")
print(verification)
print("\nMatches b:", np.allclose(verification, b))

### Question 13: Random Number Generation

Using NumPy's random module:

1. Set a random seed of 123 for reproducibility
2. Generate a 3x3 array of random integers between 1 and 100
3. Generate a 1D array of 1000 samples from a normal distribution with mean=50 and std=10
4. Calculate and print the mean and std of your normal samples (should be close to 50 and 10)
5. Randomly shuffle an array [1, 2, 3, 4, 5] and print the result

In [ ]:
# Solution

# 1. Set random seed
np.random.seed(123)
print("1. Random seed set to 123")
print()

# 2. Random integers 1-100 in 3x3 array
random_ints = np.random.randint(1, 101, size=(3, 3))
print("2. Random integers (3x3):")
print(random_ints)
print()

# 3. Normal distribution samples
normal_samples = np.random.normal(loc=50, scale=10, size=1000)
print(f"3. Generated {len(normal_samples)} normal samples")
print(f"   First 10: {normal_samples[:10]}")
print()

# 4. Calculate mean and std
sample_mean = np.mean(normal_samples)
sample_std = np.std(normal_samples)
print(f"4. Sample statistics:")
print(f"   Mean: {sample_mean:.2f} (expected: 50)")
print(f"   Std:  {sample_std:.2f} (expected: 10)")
print()

# 5. Shuffle array
arr_to_shuffle = np.array([1, 2, 3, 4, 5])
print("5. Original array:", arr_to_shuffle)
np.random.shuffle(arr_to_shuffle)  # Shuffles in place
print("   Shuffled array:", arr_to_shuffle)

---
## Section 6: Challenge Problems
---

### Question 14: Image-like Array Manipulation

Create a simple 8x8 "checkerboard" pattern array where:
- Black squares are represented by 0
- White squares are represented by 1
- The pattern alternates like a chess board

Do this WITHOUT using loops - use NumPy operations only.

Expected output (first 4 rows shown):
```
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 ...
```

In [ ]:
# Solution

# Method 1: Using indices
# Create row and column indices
rows = np.arange(8).reshape(8, 1)
cols = np.arange(8).reshape(1, 8)

# Checkerboard: (row + col) % 2
checkerboard = (rows + cols) % 2
print("Method 1 - Using index arithmetic:")
print(checkerboard)
print()

# Method 2: Using np.indices
i, j = np.indices((8, 8))
checkerboard2 = (i + j) % 2
print("Method 2 - Using np.indices:")
print(checkerboard2)
print()

# Method 3: Using tile
# Create a 2x2 tile and repeat it
tile = np.array([[0, 1], [1, 0]])
checkerboard3 = np.tile(tile, (4, 4))
print("Method 3 - Using np.tile:")
print(checkerboard3)

### Question 15: Statistical Analysis Challenge

You have exam scores for 50 students across 4 subjects:

```python
np.random.seed(42)
exam_scores = np.random.randint(40, 100, size=(50, 4))
subjects = ['Math', 'Physics', 'Chemistry', 'Biology']
```

Using NumPy operations, find:
1. The average score for each subject
2. The student (row index) with the highest total score
3. How many students scored above 80 in Math (column 0)
4. The subject with the highest average score
5. The percentage of scores that are above 70 (across all subjects)

In [ ]:
# Solution
np.random.seed(42)
exam_scores = np.random.randint(40, 100, size=(50, 4))
subjects = ['Math', 'Physics', 'Chemistry', 'Biology']

print("Exam scores shape:", exam_scores.shape)
print("First 5 students:")
print(exam_scores[:5])
print()

# 1. Average score for each subject (axis=0, across students)
subject_averages = np.mean(exam_scores, axis=0)
print("1. Average score per subject:")
for i, subj in enumerate(subjects):
    print(f"   {subj}: {subject_averages[i]:.2f}")
print()

# 2. Student with highest total score
total_scores = np.sum(exam_scores, axis=1)
best_student_idx = np.argmax(total_scores)
print(f"2. Student with highest total: Student {best_student_idx}")
print(f"   Total score: {total_scores[best_student_idx]}")
print(f"   Scores: {exam_scores[best_student_idx]}")
print()

# 3. Students scoring above 80 in Math (column 0)
math_above_80 = np.sum(exam_scores[:, 0] > 80)
print(f"3. Students scoring above 80 in Math: {math_above_80}")
print()

# 4. Subject with highest average
best_subject_idx = np.argmax(subject_averages)
print(f"4. Subject with highest average: {subjects[best_subject_idx]}")
print(f"   Average: {subject_averages[best_subject_idx]:.2f}")
print()

# 5. Percentage of scores above 70
total_scores_count = exam_scores.size
above_70_count = np.sum(exam_scores > 70)
percentage_above_70 = (above_70_count / total_scores_count) * 100
print(f"5. Percentage of scores above 70: {percentage_above_70:.2f}%")
print(f"   ({above_70_count} out of {total_scores_count} scores)")

---
## End of Test

Review your answers before submitting. Make sure all cells run without errors.