# Module 2: NumPy Comprehensive Test

This test covers all topics from Module 2 (NumPy). Complete each exercise in the provided code cells.

**Topics Covered:**
- Array Fundamentals (creation, dtypes, shape)
- Indexing and Slicing (basic, fancy, boolean)
- Array Operations (arithmetic, ufuncs, aggregations)
- Broadcasting and Vectorization
- Linear Algebra and Random Numbers

**Instructions:**
1. Run the setup cell below first
2. Read each question carefully
3. Write your solution in the provided code cell
4. Test your solution by running the cell

In [ ]:
# Setup - Run this cell first!
import numpy as np
print(f"NumPy version: {np.__version__}")
print("Setup complete!")

---
## Section 1: Array Fundamentals
---

### Question 1: Array Creation

Create the following arrays:
1. A 1D array named `arr1` containing the integers 1 through 10 (inclusive)
2. A 2D array named `arr2` with shape (3, 4) filled with zeros
3. A 1D array named `arr3` with 5 evenly spaced values between 0 and 1 (inclusive)

Print each array and its shape.

In [ ]:
# Your answer here


### Question 2: Data Types

1. Create an array `int_arr` containing [1, 2, 3, 4, 5] with dtype `int32`
2. Create an array `float_arr` by converting `int_arr` to `float64`
3. Create a boolean array `bool_arr` from the list [True, False, True, True, False]

Print each array along with its dtype.

In [ ]:
# Your answer here


### Question 3: Reshaping Arrays

1. Create an array with values 1 through 24
2. Reshape it to a 3D array with shape (2, 3, 4)
3. Flatten the 3D array back to 1D using two different methods

Print the original array, reshaped array, and both flattened versions with their shapes.

In [ ]:
# Your answer here


---
## Section 2: Indexing and Slicing
---

### Question 4: Basic Indexing and Slicing

Given the array below:
```python
matrix = np.arange(1, 26).reshape(5, 5)
```

Extract:
1. The element at row 2, column 3 (0-indexed)
2. The entire third row
3. The entire second column
4. A 2x2 subarray from the bottom-right corner

In [ ]:
# Your answer here
matrix = np.arange(1, 26).reshape(5, 5)
print("Original matrix:")
print(matrix)
print()

# Extract the required elements/slices


### Question 5: Fancy Indexing

Using the same matrix from Question 4:
1. Select rows 0, 2, and 4 simultaneously
2. Select the elements at positions (0,0), (1,2), (3,4) in a single operation
3. Reorder the columns to be [4, 2, 0, 3, 1] (reverse every other column)

In [ ]:
# Your answer here
matrix = np.arange(1, 26).reshape(5, 5)



### Question 6: Boolean Indexing

Given the array:
```python
data = np.array([12, 5, 18, 3, 21, 8, 15, 2, 19, 7])
```

1. Select all elements greater than 10
2. Select all elements that are even
3. Select all elements that are both greater than 5 AND less than 15
4. Replace all elements less than 10 with 0 (create a copy first)

In [ ]:
# Your answer here
data = np.array([12, 5, 18, 3, 21, 8, 15, 2, 19, 7])



---
## Section 3: Array Operations
---

### Question 7: Arithmetic Operations and Universal Functions

Given:
```python
a = np.array([1, 4, 9, 16, 25])
b = np.array([1, 2, 3, 4, 5])
```

Calculate and print:
1. Element-wise addition of `a` and `b`
2. Element-wise division of `a` by `b`
3. Square root of each element in `a`
4. `b` raised to the power of 2
5. Natural logarithm of `a`

In [ ]:
# Your answer here
a = np.array([1, 4, 9, 16, 25])
b = np.array([1, 2, 3, 4, 5])



### Question 8: Aggregation Functions

Given the matrix:
```python
scores = np.array([[85, 90, 78],
                   [92, 88, 95],
                   [76, 82, 89],
                   [88, 91, 84]])
```
Where rows are students and columns are subjects (Math, Science, English).

Calculate:
1. The overall mean score
2. The mean score for each student (across subjects)
3. The mean score for each subject (across students)
4. The highest score in each subject
5. The standard deviation of all scores

In [ ]:
# Your answer here
scores = np.array([[85, 90, 78],
                   [92, 88, 95],
                   [76, 82, 89],
                   [88, 91, 84]])



---
## Section 4: Broadcasting and Vectorization
---

### Question 9: Broadcasting

1. Create a 4x4 matrix of ones
2. Create a 1D array [1, 2, 3, 4]
3. Use broadcasting to:
   - Multiply each row of the matrix by the 1D array
   - Add the 1D array as a column vector to each column of the matrix

Print intermediate results to show how broadcasting works.

In [ ]:
# Your answer here


### Question 10: Vectorization Challenge

The following code uses Python loops to normalize each row of a matrix to have mean 0 and standard deviation 1:

```python
data = np.random.randn(100, 5)
normalized = np.zeros_like(data)
for i in range(data.shape[0]):
    row = data[i]
    mean = np.mean(row)
    std = np.std(row)
    normalized[i] = (row - mean) / std
```

Rewrite this using vectorized NumPy operations (no Python loops). Verify your result matches the loop version.

In [ ]:
# Your answer here
np.random.seed(42)  # For reproducibility
data = np.random.randn(100, 5)

# Loop version (for comparison)
normalized_loop = np.zeros_like(data)
for i in range(data.shape[0]):
    row = data[i]
    mean = np.mean(row)
    std = np.std(row)
    normalized_loop[i] = (row - mean) / std

# Your vectorized version here


---
## Section 5: Linear Algebra and Random Numbers
---

### Question 11: Matrix Operations

Given:
```python
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
```

Calculate:
1. Matrix multiplication of A and B (using @ operator or np.dot)
2. The transpose of A
3. The determinant of A
4. The inverse of A
5. Verify that A @ A_inverse equals the identity matrix

In [ ]:
# Your answer here
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])



### Question 12: Solving Linear Systems

Solve the following system of linear equations using NumPy:

```
2x + 3y - z = 1
4x + y + 2z = 2  
3x + 2y + 3z = 3
```

Express this in matrix form (Ax = b) and solve for x, y, z. Verify your solution by computing A @ x.

In [ ]:
# Your answer here


### Question 13: Random Number Generation

Using NumPy's random module:

1. Set a random seed of 123 for reproducibility
2. Generate a 3x3 array of random integers between 1 and 100
3. Generate a 1D array of 1000 samples from a normal distribution with mean=50 and std=10
4. Calculate and print the mean and std of your normal samples (should be close to 50 and 10)
5. Randomly shuffle an array [1, 2, 3, 4, 5] and print the result

In [ ]:
# Your answer here


---
## Section 6: Challenge Problems
---

### Question 14: Image-like Array Manipulation

Create a simple 8x8 "checkerboard" pattern array where:
- Black squares are represented by 0
- White squares are represented by 1
- The pattern alternates like a chess board

Do this WITHOUT using loops - use NumPy operations only.

Expected output (first 4 rows shown):
```
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 ...
```

In [ ]:
# Your answer here


### Question 15: Statistical Analysis Challenge

You have exam scores for 50 students across 4 subjects:

```python
np.random.seed(42)
exam_scores = np.random.randint(40, 100, size=(50, 4))
subjects = ['Math', 'Physics', 'Chemistry', 'Biology']
```

Using NumPy operations, find:
1. The average score for each subject
2. The student (row index) with the highest total score
3. How many students scored above 80 in Math (column 0)
4. The subject with the highest average score
5. The percentage of scores that are above 70 (across all subjects)

In [ ]:
# Your answer here
np.random.seed(42)
exam_scores = np.random.randint(40, 100, size=(50, 4))
subjects = ['Math', 'Physics', 'Chemistry', 'Biology']



---
## End of Test

Review your answers before submitting. Make sure all cells run without errors.